# Generated by Django 4.1.5 on 2023-01-09 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='my_app.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='books',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='my_app.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='my_app.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='my_app.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='my_app.position'),
            preserve_default=False,
        ),
    ]
